# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...4.2)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS SDL3_mixer::SDL3_mixer-shared SDL3_mixer::ogg SDL3_mixer::opus SDL3_mixer::opusfile SDL3_mixer::vorbis SDL3_mixer::vorbisfile SDL3_mixer::FLAC SDL3_mixer::gme_shared SDL3_mixer::xmp_shared SDL3_mixer::libmpg123 SDL3_mixer::WavPack)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target SDL3_mixer::SDL3_mixer-shared
add_library(SDL3_mixer::SDL3_mixer-shared SHARED IMPORTED)

set_target_properties(SDL3_mixer::SDL3_mixer-shared PROPERTIES
  COMPATIBLE_INTERFACE_BOOL "SDL3_SHARED"
  INTERFACE_INCLUDE_DIRECTORIES "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/include"
  INTERFACE_LINK_LIBRARIES "SDL3::Headers"
  INTERFACE_SDL3_SHARED "ON"
)

# Create imported target SDL3_mixer::ogg
add_library(SDL3_mixer::ogg SHARED IMPORTED)

set_target_properties(SDL3_mixer::ogg PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/external/ogg/include;D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/ogg-build/include"
)

# Create imported target SDL3_mixer::opus
add_library(SDL3_mixer::opus SHARED IMPORTED)

set_target_properties(SDL3_mixer::opus PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/external/opus/include"
)

# Create imported target SDL3_mixer::opusfile
add_library(SDL3_mixer::opusfile SHARED IMPORTED)

set_target_properties(SDL3_mixer::opusfile PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/external/opusfile/include"
  INTERFACE_LINK_LIBRARIES "SDL3_mixer::ogg;SDL3_mixer::opus;\$<\$<BOOL:>:m>"
)

# Create imported target SDL3_mixer::vorbis
add_library(SDL3_mixer::vorbis SHARED IMPORTED)

set_target_properties(SDL3_mixer::vorbis PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/external/vorbis/include"
  INTERFACE_LINK_LIBRARIES "SDL3_mixer::ogg"
)

# Create imported target SDL3_mixer::vorbisfile
add_library(SDL3_mixer::vorbisfile SHARED IMPORTED)

set_target_properties(SDL3_mixer::vorbisfile PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/external/vorbis/include"
  INTERFACE_LINK_LIBRARIES "SDL3_mixer::vorbis"
)

# Create imported target SDL3_mixer::FLAC
add_library(SDL3_mixer::FLAC SHARED IMPORTED)

set_target_properties(SDL3_mixer::FLAC PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<NOT:\$<BOOL:ON>>:FLAC__NO_DLL>"
  INTERFACE_INCLUDE_DIRECTORIES "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/external/flac/include"
  INTERFACE_LINK_LIBRARIES "\$<\$<BOOL:>:m>"
)

# Create imported target SDL3_mixer::gme_shared
add_library(SDL3_mixer::gme_shared SHARED IMPORTED)

set_target_properties(SDL3_mixer::gme_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/external/libgme/gme/.."
)

# Create imported target SDL3_mixer::xmp_shared
add_library(SDL3_mixer::xmp_shared SHARED IMPORTED)

set_target_properties(SDL3_mixer::xmp_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/external/libxmp/include"
)

# Create imported target SDL3_mixer::libmpg123
add_library(SDL3_mixer::libmpg123 SHARED IMPORTED)

set_target_properties(SDL3_mixer::libmpg123 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/external/mpg123/ports/cmake/src/libmpg123/../../../../src/include/;D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libmpg123-build/ports/cmake/src/libmpg123"
)

# Create imported target SDL3_mixer::WavPack
add_library(SDL3_mixer::WavPack SHARED IMPORTED)

set_target_properties(SDL3_mixer::WavPack PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/external/wavpack/include"
)

# Import target "SDL3_mixer::SDL3_mixer-shared" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_mixer::SDL3_mixer-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_mixer::SDL3_mixer-shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/RelWithDebInfo/SDL3_mixer.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELWITHDEBINFO "SDL3::SDL3-shared"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/RelWithDebInfo/SDL3_mixer.dll"
  )

# Import target "SDL3_mixer::ogg" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_mixer::ogg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_mixer::ogg PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/ogg-build/RelWithDebInfo/ogg.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/ogg-build/RelWithDebInfo/ogg-0.dll"
  )

# Import target "SDL3_mixer::opus" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_mixer::opus APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_mixer::opus PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/opus-build/RelWithDebInfo/opus.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/opus-build/RelWithDebInfo/opus-0.dll"
  )

# Import target "SDL3_mixer::opusfile" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_mixer::opusfile APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_mixer::opusfile PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/opusfile-build/RelWithDebInfo/opusfile.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/opusfile-build/RelWithDebInfo/opusfile-0.dll"
  )

# Import target "SDL3_mixer::vorbis" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_mixer::vorbis APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_mixer::vorbis PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/vorbis-build/lib/RelWithDebInfo/vorbis.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/vorbis-build/lib/RelWithDebInfo/vorbis-0.dll"
  )

# Import target "SDL3_mixer::vorbisfile" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_mixer::vorbisfile APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_mixer::vorbisfile PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/vorbis-build/lib/RelWithDebInfo/vorbisfile.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/vorbis-build/lib/RelWithDebInfo/vorbisfile-3.dll"
  )

# Import target "SDL3_mixer::FLAC" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_mixer::FLAC APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_mixer::FLAC PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/flac-build/src/libFLAC/RelWithDebInfo/FLAC.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELWITHDEBINFO "SDL3_mixer::ogg"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/flac-build/src/libFLAC/RelWithDebInfo/FLAC-8.dll"
  )

# Import target "SDL3_mixer::gme_shared" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_mixer::gme_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_mixer::gme_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libgme-build/gme/RelWithDebInfo/gme.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libgme-build/gme/RelWithDebInfo/gme.dll"
  )

# Import target "SDL3_mixer::xmp_shared" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_mixer::xmp_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_mixer::xmp_shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libxmp-build/RelWithDebInfo/libxmp.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libxmp-build/RelWithDebInfo/libxmp.dll"
  )

# Import target "SDL3_mixer::libmpg123" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_mixer::libmpg123 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_mixer::libmpg123 PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libmpg123-build/ports/cmake/src/libmpg123/RelWithDebInfo/mpg123.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libmpg123-build/ports/cmake/src/libmpg123/RelWithDebInfo/mpg123-0.dll"
  )

# Import target "SDL3_mixer::WavPack" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_mixer::WavPack APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_mixer::WavPack PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/wavpack-build/RelWithDebInfo/wavpackdll.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/wavpack-build/RelWithDebInfo/wavpackdll.dll"
  )

# Import target "SDL3_mixer::SDL3_mixer-shared" for configuration "Debug"
set_property(TARGET SDL3_mixer::SDL3_mixer-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_mixer::SDL3_mixer-shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/Debug/SDL3_mixer.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_DEBUG "SDL3::SDL3-shared"
  IMPORTED_LOCATION_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/Debug/SDL3_mixer.dll"
  )

# Import target "SDL3_mixer::ogg" for configuration "Debug"
set_property(TARGET SDL3_mixer::ogg APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_mixer::ogg PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/ogg-build/Debug/ogg.lib"
  IMPORTED_LOCATION_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/ogg-build/Debug/ogg-0.dll"
  )

# Import target "SDL3_mixer::opus" for configuration "Debug"
set_property(TARGET SDL3_mixer::opus APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_mixer::opus PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/opus-build/Debug/opus.lib"
  IMPORTED_LOCATION_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/opus-build/Debug/opus-0.dll"
  )

# Import target "SDL3_mixer::opusfile" for configuration "Debug"
set_property(TARGET SDL3_mixer::opusfile APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_mixer::opusfile PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/opusfile-build/Debug/opusfile.lib"
  IMPORTED_LOCATION_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/opusfile-build/Debug/opusfile-0.dll"
  )

# Import target "SDL3_mixer::vorbis" for configuration "Debug"
set_property(TARGET SDL3_mixer::vorbis APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_mixer::vorbis PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/vorbis-build/lib/Debug/vorbis.lib"
  IMPORTED_LOCATION_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/vorbis-build/lib/Debug/vorbis-0.dll"
  )

# Import target "SDL3_mixer::vorbisfile" for configuration "Debug"
set_property(TARGET SDL3_mixer::vorbisfile APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_mixer::vorbisfile PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/vorbis-build/lib/Debug/vorbisfile.lib"
  IMPORTED_LOCATION_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/vorbis-build/lib/Debug/vorbisfile-3.dll"
  )

# Import target "SDL3_mixer::FLAC" for configuration "Debug"
set_property(TARGET SDL3_mixer::FLAC APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_mixer::FLAC PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/flac-build/src/libFLAC/Debug/FLAC.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_DEBUG "SDL3_mixer::ogg"
  IMPORTED_LOCATION_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/flac-build/src/libFLAC/Debug/FLAC-8.dll"
  )

# Import target "SDL3_mixer::gme_shared" for configuration "Debug"
set_property(TARGET SDL3_mixer::gme_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_mixer::gme_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libgme-build/gme/Debug/gme.lib"
  IMPORTED_LOCATION_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libgme-build/gme/Debug/gme.dll"
  )

# Import target "SDL3_mixer::xmp_shared" for configuration "Debug"
set_property(TARGET SDL3_mixer::xmp_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_mixer::xmp_shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libxmp-build/Debug/libxmp.lib"
  IMPORTED_LOCATION_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libxmp-build/Debug/libxmp.dll"
  )

# Import target "SDL3_mixer::libmpg123" for configuration "Debug"
set_property(TARGET SDL3_mixer::libmpg123 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_mixer::libmpg123 PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libmpg123-build/ports/cmake/src/libmpg123/Debug/mpg123.lib"
  IMPORTED_LOCATION_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libmpg123-build/ports/cmake/src/libmpg123/Debug/mpg123-0.dll"
  )

# Import target "SDL3_mixer::WavPack" for configuration "Debug"
set_property(TARGET SDL3_mixer::WavPack APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_mixer::WavPack PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/wavpack-build/Debug/wavpackdll.lib"
  IMPORTED_LOCATION_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/wavpack-build/Debug/wavpackdll.dll"
  )

# Import target "SDL3_mixer::SDL3_mixer-shared" for configuration "Release"
set_property(TARGET SDL3_mixer::SDL3_mixer-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_mixer::SDL3_mixer-shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/Release/SDL3_mixer.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "SDL3::SDL3-shared"
  IMPORTED_LOCATION_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/Release/SDL3_mixer.dll"
  )

# Import target "SDL3_mixer::ogg" for configuration "Release"
set_property(TARGET SDL3_mixer::ogg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_mixer::ogg PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/ogg-build/Release/ogg.lib"
  IMPORTED_LOCATION_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/ogg-build/Release/ogg-0.dll"
  )

# Import target "SDL3_mixer::opus" for configuration "Release"
set_property(TARGET SDL3_mixer::opus APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_mixer::opus PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/opus-build/Release/opus.lib"
  IMPORTED_LOCATION_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/opus-build/Release/opus-0.dll"
  )

# Import target "SDL3_mixer::opusfile" for configuration "Release"
set_property(TARGET SDL3_mixer::opusfile APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_mixer::opusfile PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/opusfile-build/Release/opusfile.lib"
  IMPORTED_LOCATION_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/opusfile-build/Release/opusfile-0.dll"
  )

# Import target "SDL3_mixer::vorbis" for configuration "Release"
set_property(TARGET SDL3_mixer::vorbis APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_mixer::vorbis PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/vorbis-build/lib/Release/vorbis.lib"
  IMPORTED_LOCATION_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/vorbis-build/lib/Release/vorbis-0.dll"
  )

# Import target "SDL3_mixer::vorbisfile" for configuration "Release"
set_property(TARGET SDL3_mixer::vorbisfile APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_mixer::vorbisfile PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/vorbis-build/lib/Release/vorbisfile.lib"
  IMPORTED_LOCATION_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/vorbis-build/lib/Release/vorbisfile-3.dll"
  )

# Import target "SDL3_mixer::FLAC" for configuration "Release"
set_property(TARGET SDL3_mixer::FLAC APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_mixer::FLAC PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/flac-build/src/libFLAC/Release/FLAC.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "SDL3_mixer::ogg"
  IMPORTED_LOCATION_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/flac-build/src/libFLAC/Release/FLAC-8.dll"
  )

# Import target "SDL3_mixer::gme_shared" for configuration "Release"
set_property(TARGET SDL3_mixer::gme_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_mixer::gme_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libgme-build/gme/Release/gme.lib"
  IMPORTED_LOCATION_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libgme-build/gme/Release/gme.dll"
  )

# Import target "SDL3_mixer::xmp_shared" for configuration "Release"
set_property(TARGET SDL3_mixer::xmp_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_mixer::xmp_shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libxmp-build/Release/libxmp.lib"
  IMPORTED_LOCATION_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libxmp-build/Release/libxmp.dll"
  )

# Import target "SDL3_mixer::libmpg123" for configuration "Release"
set_property(TARGET SDL3_mixer::libmpg123 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_mixer::libmpg123 PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libmpg123-build/ports/cmake/src/libmpg123/Release/mpg123.lib"
  IMPORTED_LOCATION_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libmpg123-build/ports/cmake/src/libmpg123/Release/mpg123-0.dll"
  )

# Import target "SDL3_mixer::WavPack" for configuration "Release"
set_property(TARGET SDL3_mixer::WavPack APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_mixer::WavPack PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/wavpack-build/Release/wavpackdll.lib"
  IMPORTED_LOCATION_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/wavpack-build/Release/wavpackdll.dll"
  )

# Import target "SDL3_mixer::SDL3_mixer-shared" for configuration "MinSizeRel"
set_property(TARGET SDL3_mixer::SDL3_mixer-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_mixer::SDL3_mixer-shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/MinSizeRel/SDL3_mixer.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_MINSIZEREL "SDL3::SDL3-shared"
  IMPORTED_LOCATION_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/MinSizeRel/SDL3_mixer.dll"
  )

# Import target "SDL3_mixer::ogg" for configuration "MinSizeRel"
set_property(TARGET SDL3_mixer::ogg APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_mixer::ogg PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/ogg-build/MinSizeRel/ogg.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/ogg-build/MinSizeRel/ogg-0.dll"
  )

# Import target "SDL3_mixer::opus" for configuration "MinSizeRel"
set_property(TARGET SDL3_mixer::opus APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_mixer::opus PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/opus-build/MinSizeRel/opus.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/opus-build/MinSizeRel/opus-0.dll"
  )

# Import target "SDL3_mixer::opusfile" for configuration "MinSizeRel"
set_property(TARGET SDL3_mixer::opusfile APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_mixer::opusfile PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/opusfile-build/MinSizeRel/opusfile.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/opusfile-build/MinSizeRel/opusfile-0.dll"
  )

# Import target "SDL3_mixer::vorbis" for configuration "MinSizeRel"
set_property(TARGET SDL3_mixer::vorbis APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_mixer::vorbis PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/vorbis-build/lib/MinSizeRel/vorbis.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/vorbis-build/lib/MinSizeRel/vorbis-0.dll"
  )

# Import target "SDL3_mixer::vorbisfile" for configuration "MinSizeRel"
set_property(TARGET SDL3_mixer::vorbisfile APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_mixer::vorbisfile PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/vorbis-build/lib/MinSizeRel/vorbisfile.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/vorbis-build/lib/MinSizeRel/vorbisfile-3.dll"
  )

# Import target "SDL3_mixer::FLAC" for configuration "MinSizeRel"
set_property(TARGET SDL3_mixer::FLAC APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_mixer::FLAC PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/flac-build/src/libFLAC/MinSizeRel/FLAC.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_MINSIZEREL "SDL3_mixer::ogg"
  IMPORTED_LOCATION_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/flac-build/src/libFLAC/MinSizeRel/FLAC-8.dll"
  )

# Import target "SDL3_mixer::gme_shared" for configuration "MinSizeRel"
set_property(TARGET SDL3_mixer::gme_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_mixer::gme_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libgme-build/gme/MinSizeRel/gme.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libgme-build/gme/MinSizeRel/gme.dll"
  )

# Import target "SDL3_mixer::xmp_shared" for configuration "MinSizeRel"
set_property(TARGET SDL3_mixer::xmp_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_mixer::xmp_shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libxmp-build/MinSizeRel/libxmp.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libxmp-build/MinSizeRel/libxmp.dll"
  )

# Import target "SDL3_mixer::libmpg123" for configuration "MinSizeRel"
set_property(TARGET SDL3_mixer::libmpg123 APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_mixer::libmpg123 PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libmpg123-build/ports/cmake/src/libmpg123/MinSizeRel/mpg123.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/libmpg123-build/ports/cmake/src/libmpg123/MinSizeRel/mpg123-0.dll"
  )

# Import target "SDL3_mixer::WavPack" for configuration "MinSizeRel"
set_property(TARGET SDL3_mixer::WavPack APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_mixer::WavPack PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/wavpack-build/MinSizeRel/wavpackdll.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_mixer/build_wn/external/wavpack-build/MinSizeRel/wavpackdll.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
