# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...4.2)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS SDL3_image::SDL3_image-shared SDL3_image::external_libpng SDL3_image::external_libtiff SDL3_image::external_libwebp SDL3_image::external_webpdemux SDL3_image::external_libwebpmux)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target SDL3_image::SDL3_image-shared
add_library(SDL3_image::SDL3_image-shared SHARED IMPORTED)

set_target_properties(SDL3_image::SDL3_image-shared PROPERTIES
  COMPATIBLE_INTERFACE_BOOL "SDL3_SHARED"
  INTERFACE_INCLUDE_DIRECTORIES "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/include"
  INTERFACE_LINK_LIBRARIES "SDL3::Headers"
  INTERFACE_SDL3_SHARED "TRUE"
)

# Create imported target SDL3_image::external_libpng
add_library(SDL3_image::external_libpng SHARED IMPORTED)

set_target_properties(SDL3_image::external_libpng PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/external/libpng;D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libpng-build"
)

# Create imported target SDL3_image::external_libtiff
add_library(SDL3_image::external_libtiff SHARED IMPORTED)

set_target_properties(SDL3_image::external_libtiff PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/external/libtiff/libtiff;D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libtiff-build/libtiff"
)

# Create imported target SDL3_image::external_libwebp
add_library(SDL3_image::external_libwebp SHARED IMPORTED)

set_target_properties(SDL3_image::external_libwebp PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/external/libwebp/src"
)

# Create imported target SDL3_image::external_webpdemux
add_library(SDL3_image::external_webpdemux SHARED IMPORTED)

set_target_properties(SDL3_image::external_webpdemux PROPERTIES
  INTERFACE_LINK_LIBRARIES "SDL3_image::external_libwebp"
)

# Create imported target SDL3_image::external_libwebpmux
add_library(SDL3_image::external_libwebpmux SHARED IMPORTED)

set_target_properties(SDL3_image::external_libwebpmux PROPERTIES
  INTERFACE_LINK_LIBRARIES "SDL3_image::external_libwebp"
)

# Import target "SDL3_image::SDL3_image-shared" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_image::SDL3_image-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_image::SDL3_image-shared PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/RelWithDebInfo/SDL3_image.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELWITHDEBINFO "SDL3::SDL3-shared"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/RelWithDebInfo/SDL3_image.dll"
  )

# Import target "SDL3_image::external_libpng" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_image::external_libpng APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_image::external_libpng PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libpng-build/RelWithDebInfo/libpng16-16.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libpng-build/RelWithDebInfo/libpng16-16.dll"
  )

# Import target "SDL3_image::external_libtiff" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_image::external_libtiff APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_image::external_libtiff PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libtiff-build/libtiff/RelWithDebInfo/tiff.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libtiff-build/libtiff/RelWithDebInfo/tiff.dll"
  )

# Import target "SDL3_image::external_libwebp" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_image::external_libwebp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_image::external_libwebp PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/RelWithDebInfo/libwebp.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/RelWithDebInfo/libwebp.dll"
  )

# Import target "SDL3_image::external_webpdemux" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_image::external_webpdemux APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_image::external_webpdemux PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/RelWithDebInfo/libwebpdemux.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/RelWithDebInfo/libwebpdemux.dll"
  )

# Import target "SDL3_image::external_libwebpmux" for configuration "RelWithDebInfo"
set_property(TARGET SDL3_image::external_libwebpmux APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SDL3_image::external_libwebpmux PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/RelWithDebInfo/libwebpmux.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/RelWithDebInfo/libwebpmux.dll"
  )

# Import target "SDL3_image::SDL3_image-shared" for configuration "Debug"
set_property(TARGET SDL3_image::SDL3_image-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_image::SDL3_image-shared PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/Debug/SDL3_image.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_DEBUG "SDL3::SDL3-shared"
  IMPORTED_LOCATION_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/Debug/SDL3_image.dll"
  )

# Import target "SDL3_image::external_libpng" for configuration "Debug"
set_property(TARGET SDL3_image::external_libpng APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_image::external_libpng PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libpng-build/Debug/libpng16-16.lib"
  IMPORTED_LOCATION_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libpng-build/Debug/libpng16-16.dll"
  )

# Import target "SDL3_image::external_libtiff" for configuration "Debug"
set_property(TARGET SDL3_image::external_libtiff APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_image::external_libtiff PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libtiff-build/libtiff/Debug/tiffd.lib"
  IMPORTED_LOCATION_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libtiff-build/libtiff/Debug/tiffd.dll"
  )

# Import target "SDL3_image::external_libwebp" for configuration "Debug"
set_property(TARGET SDL3_image::external_libwebp APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_image::external_libwebp PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/Debug/libwebp.lib"
  IMPORTED_LOCATION_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/Debug/libwebp.dll"
  )

# Import target "SDL3_image::external_webpdemux" for configuration "Debug"
set_property(TARGET SDL3_image::external_webpdemux APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_image::external_webpdemux PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/Debug/libwebpdemux.lib"
  IMPORTED_LOCATION_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/Debug/libwebpdemux.dll"
  )

# Import target "SDL3_image::external_libwebpmux" for configuration "Debug"
set_property(TARGET SDL3_image::external_libwebpmux APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(SDL3_image::external_libwebpmux PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/Debug/libwebpmux.lib"
  IMPORTED_LOCATION_DEBUG "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/Debug/libwebpmux.dll"
  )

# Import target "SDL3_image::SDL3_image-shared" for configuration "Release"
set_property(TARGET SDL3_image::SDL3_image-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_image::SDL3_image-shared PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/Release/SDL3_image.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "SDL3::SDL3-shared"
  IMPORTED_LOCATION_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/Release/SDL3_image.dll"
  )

# Import target "SDL3_image::external_libpng" for configuration "Release"
set_property(TARGET SDL3_image::external_libpng APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_image::external_libpng PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libpng-build/Release/libpng16-16.lib"
  IMPORTED_LOCATION_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libpng-build/Release/libpng16-16.dll"
  )

# Import target "SDL3_image::external_libtiff" for configuration "Release"
set_property(TARGET SDL3_image::external_libtiff APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_image::external_libtiff PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libtiff-build/libtiff/Release/tiff.lib"
  IMPORTED_LOCATION_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libtiff-build/libtiff/Release/tiff.dll"
  )

# Import target "SDL3_image::external_libwebp" for configuration "Release"
set_property(TARGET SDL3_image::external_libwebp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_image::external_libwebp PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/Release/libwebp.lib"
  IMPORTED_LOCATION_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/Release/libwebp.dll"
  )

# Import target "SDL3_image::external_webpdemux" for configuration "Release"
set_property(TARGET SDL3_image::external_webpdemux APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_image::external_webpdemux PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/Release/libwebpdemux.lib"
  IMPORTED_LOCATION_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/Release/libwebpdemux.dll"
  )

# Import target "SDL3_image::external_libwebpmux" for configuration "Release"
set_property(TARGET SDL3_image::external_libwebpmux APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(SDL3_image::external_libwebpmux PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/Release/libwebpmux.lib"
  IMPORTED_LOCATION_RELEASE "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/Release/libwebpmux.dll"
  )

# Import target "SDL3_image::SDL3_image-shared" for configuration "MinSizeRel"
set_property(TARGET SDL3_image::SDL3_image-shared APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_image::SDL3_image-shared PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/MinSizeRel/SDL3_image.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_MINSIZEREL "SDL3::SDL3-shared"
  IMPORTED_LOCATION_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/MinSizeRel/SDL3_image.dll"
  )

# Import target "SDL3_image::external_libpng" for configuration "MinSizeRel"
set_property(TARGET SDL3_image::external_libpng APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_image::external_libpng PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libpng-build/MinSizeRel/libpng16-16.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libpng-build/MinSizeRel/libpng16-16.dll"
  )

# Import target "SDL3_image::external_libtiff" for configuration "MinSizeRel"
set_property(TARGET SDL3_image::external_libtiff APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_image::external_libtiff PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libtiff-build/libtiff/MinSizeRel/tiff.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libtiff-build/libtiff/MinSizeRel/tiff.dll"
  )

# Import target "SDL3_image::external_libwebp" for configuration "MinSizeRel"
set_property(TARGET SDL3_image::external_libwebp APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_image::external_libwebp PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/MinSizeRel/libwebp.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/MinSizeRel/libwebp.dll"
  )

# Import target "SDL3_image::external_webpdemux" for configuration "MinSizeRel"
set_property(TARGET SDL3_image::external_webpdemux APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_image::external_webpdemux PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/MinSizeRel/libwebpdemux.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/MinSizeRel/libwebpdemux.dll"
  )

# Import target "SDL3_image::external_libwebpmux" for configuration "MinSizeRel"
set_property(TARGET SDL3_image::external_libwebpmux APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(SDL3_image::external_libwebpmux PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/MinSizeRel/libwebpmux.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/BrishkamalMaterial/ColonelDocuments/CodeHub/Projects/Cpp/baaghchaal/libraries/SDL3_image/build_wn/external/libwebp-build/MinSizeRel/libwebpmux.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
