#pragma once

enum Rules{
  KILLED_GOATS = 5,
  TIGERS_TRAPPED = 4
};

// SCORING WEIGHTS FOR THE BOT EVALUATION 
enum Scores{
  GOATS_KILLED = 250, // EACH GOAT KILLED SCORE   
  TIGERS_MOBILITY = 18, // MORE MOVE, MORE ADVANTAGE FOR TIGER
  TIGER_CAPTURE = 100, // FOR EACH GOATS THAT CAN BE CAPTURED
  TIGER_TRAPPED = 200, // EACH TIGER TRAPPED
  TIGER_CENTER = 35, // MORE THE CENTERED, MORE ADVANAAGE I THINK
  TIGER_EDGE = 8, // EDGE POSTION ARE NOT FINE
  GOAT_MOBILITY = 4, // GOAT MOVEMENT FREEDOM
  GOAT_VULNERABLE = 50, // GOATS IN DANGER OF BEING CAPTURED
  GOAT_CLUSTER = 25, // CLUSTERED GOATS CAN TRAP TIGER
  TIGER_ESCAPE = 18, // TIGER FREEDOM
  TIGER_DANGER = 30, // NOT USED NOW
  GOAT_RESTRICT = 20, // RESTRICTING TIGER MOVEMENT IS GOOD FOR GOATS
  GOATS_IN_HAND = 3, // HAVING MORE GOATS TO PLACE
  BOT_WON = 10000000,
  HUMAN_WON = -10000000
};

// EXTRA SCORING FOR SPECIFIC GAME SITUATIONS
enum ExtraScores {
  GOAT_ADVANCED = 2,
  GOAT_BLOCKING = 20, // GOATS BLOCKING TIGER CAPTURE PATHS
  GOAT_SAFE_PLACEMENT = 40, // SAFE GOAT PLACEMENTS ARE GOOD
  GOAT_DANGER_PLACEMENT = 60, // DANGEROUS PLACEMENTS SHOULD BE AVOIDED
  TIGER_COUNT_BONUS = 25, // HAVING MORE ACTIVE TIGERS
  GOAT_COUNT_PENALTY = 10 // FEWER GOATS MEANS TIGER IS WINNING
};
