#pragma once

enum Rules{
  KILLED_GOATS = 5,
  TIGERS_TRAPPED = 4
};

enum Scores{
  GOATS_KILLED = 180,
  TIGERS_MOBILITY = 18,
  TIGER_CAPTURE = 85,
  TIGER_TRAPPED = 180,
  TIGER_CENTER = 35,
  TIGER_EDGE = 8,
  GOAT_MOBILITY = 4,
  GOAT_VULNERABLE = 35,
  GOAT_CLUSTER = 8,
  TIGER_ESCAPE = 12,
  TIGER_DANGER = 30,
  GOAT_RESTRICT = 15,
  GOATS_IN_HAND = 3,
  BOT_WON = 10000000,
  HUMAN_WON = -10000000
};

enum ExtraScores {
  GOAT_ADVANCED = 2,
  GOAT_BLOCKING = 12,
  GOAT_SAFE_PLACEMENT = 15,
  GOAT_DANGER_PLACEMENT = 60,
  TIGER_COUNT_BONUS = 3,
  GOAT_COUNT_PENALTY = 1
};
